[project]
name = "abs-ard-hoerspieldb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bs4>=0.0.2",
    "fastapi[standard]>=0.115.8",
    "lxml>=5.3.1",
    "requests>=2.32.3",
]
